#!/usr/bin/env python3
"""Writes the cloud-init user data that turns a fresh Ubuntu 24.04 server into the OpenTPW server.

    python3 deploy/make-cloud-init.py --domain play.opentpw.io > user-data.yml

Paste the output into the "Cloud config" field when creating the server (or pass it as user_data
through the Hetzner API). On first boot it installs Docker, turns off SSH password logins, places
the files of this folder in /opt/opentpw, enables the nightly update and backup timers and starts
the server. See docs/SERVER.md.
"""
import argparse
import pathlib
import re

HERE = pathlib.Path(__file__).resolve().parent
UNITS = ["opentpw-update.service", "opentpw-update.timer", "opentpw-backup.service", "opentpw-backup.timer"]
# The .NET images run as this user (APP_UID); it must own the data folder.
APP_UID = 1654


def block(path: str, content: str, permissions: str = "0644") -> str:
    body = "".join(f"      {line}\n" if line else "\n" for line in content.rstrip("\n").split("\n"))
    return f"  - path: {path}\n    permissions: '{permissions}'\n    content: |\n{body}"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--domain", required=True, help="the server's domain, e.g. play.opentpw.io")
    parser.add_argument("--server-name", default="OpenTPW")
    parser.add_argument("--message", default="Welcome to the OpenTPW server. Be nice.")
    parser.add_argument("--image-tag", default="latest", help="latest follows releases, main follows main")
    args = parser.parse_args()
    if not re.fullmatch(r"[a-z0-9.-]+", args.domain):
        parser.error("--domain must be a plain host name")
    for value in (args.server_name, args.message, args.image_tag):
        if "\n" in value or '"' in value:
            parser.error("settings must be single lines without double quotes")

    env = (f"OPENTPW_DOMAIN={args.domain}\n"
           f'OPENTPW_SERVER_NAME="{args.server_name}"\n'
           f'OPENTPW_MESSAGE="{args.message}"\n'
           f"OPENTPW_IMAGE_TAG={args.image_tag}\n")
    files = [
        block("/opt/opentpw/compose.yml", (HERE / "compose.yml").read_text()),
        block("/opt/opentpw/Caddyfile", (HERE / "Caddyfile").read_text()),
        block("/opt/opentpw/.env", env, "0600"),
        block("/etc/ssh/sshd_config.d/10-opentpw.conf", "PasswordAuthentication no\nKbdInteractiveAuthentication no\nPermitRootLogin prohibit-password\n"),
    ] + [block(f"/etc/systemd/system/{unit}", (HERE / unit).read_text()) for unit in UNITS]

    print("#cloud-config")
    print("# OpenTPW server, generated by deploy/make-cloud-init.py (docs/SERVER.md).")
    print("package_update: true")
    print("package_upgrade: true")
    print("packages:\n  - docker.io\n  - docker-compose-v2\n  - unattended-upgrades")
    print("write_files:")
    print("".join(files), end="")
    print("runcmd:")
    for command in [
        "systemctl restart ssh",
        "systemctl enable --now docker",
        f"mkdir -p /opt/opentpw/data && chown {APP_UID}:{APP_UID} /opt/opentpw/data",
        "systemctl daemon-reload",
        "systemctl enable --now opentpw-update.timer opentpw-backup.timer",
        "cd /opt/opentpw && docker compose up -d",
    ]:
        print(f"  - [ sh, -c, \"{command}\" ]")


if __name__ == "__main__":
    main()
