<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="animation/**/*.cs" />
    <Compile Include="animation/OriginalAnimationState.cs" />
    <ProjectReference Include="../../../../source/OpenTPW.Files/OpenTPW.Files.csproj" />
  </ItemGroup>
</Project>
